### ISSUE TITLE
🐞 [Bug]: CLI Hangs at Initial Plotting

### ISSUE THREAD

**Issue by Screem0033** [subspace/pulsar#158]
### What happened?

Error after update v0.1.12 
there are errors and rewards do not come to the wallet
wallet: SubWallet
<img width="337" alt="image" src="https://user-images.githubusercontent.com/129008917/228627038-f33c46c6-a3a8-4c73-bbb9-8b1babcd0192.png">

![image](https://user-images.githubusercontent.com/129008917/228626408-6db9efe3-8309-49fe-ac18-139b2e0bff29.png)

### Version

v0.1.12

### platform

- [X] linux
- [ ] windows
- [ ] macos

### Expected behavior

My friends node works well and rewards come

I only get errors

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ozgunozerk** [comment]
Hello! Thanks for the submission.
This is a known bug, also reported in the forum: https://forum.subspace.network/t/basic-cli-hangs-at-initial-plotting/1320

This bug is reported at: https://github.com/subspace/subspace/issues/1310
After this issue is fixed on the monorepo side, we will quickly import the changes into SDK and CLI ⚡

**Comment by iabudumilionerom** [comment]
Hello team, after 3 weeks any update ? the mistake is still here ! 0 TSSC after 3 weeks that I run the node !

**Comment by ozgunozerk** [comment]
@iabudumilionerom 
Which version are you using, this issue should have been resolved with 0.2.0 and later
